//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Users
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableTest
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string ThirdName { get; set; }
        public string JobPosition { get; set; }
        public int Salary { get; set; }
        public System.DateTime HireDate { get; set; }
        public Nullable<System.DateTime> FireDate { get; set; }
    }
}
